# Generated by Django 4.2.19 on 2025-03-24 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=1024)),
                ('date', models.DateField(default=datetime.datetime(2025, 3, 24, 20, 14, 9, 293988))),
                ('time', models.TimeField(default=datetime.datetime(2025, 3, 24, 20, 14, 9, 293999))),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
