# Generated by Django 4.2.19 on 2025-03-24 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activitymodel_delete_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
