# Generated by Django 4.2.19 on 2025-03-25 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activitymodel_date_alter_activitymodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='activitymodel',
            name='time',
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
